name: Deployment

on: [push]


jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      # Wait for lint and test workflow to complete
      - name: Wait for other checks to succeed
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: ${{ github.ref }}
          running-workflow-name: 'Deployment'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 40
          check-regexp: .?_and_test

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          export_default_credentials: true
      
      # Build docker image
      - name: Build
        run: |-
          docker build -t eu.gcr.io/$PROJECT_ID/$GCR_NAME:$GITHUB_SHA .
      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker -q

      # Push image to Google Container Registry
      - name: Push
        run: |-
          docker push eu.gcr.io/$PROJECT_ID/$GCR_NAME:$GITHUB_SHA

  deploy_to_test:
    name: Deploy Test Server to Google Cloud Run
    runs-on: ubuntu-latest
    needs: [build_and_push_image]
    steps:
      - name: Checkout working branches
        uses: actions/checkout@v2
      
      - name: Get GCP project credential
        run: echo "this is just work in progress"
